### PR TITLE
WIP: rebase UX/tokens to use the vite work in main

### PR DESCRIPTION
**Pull request by SvenDowideit**
works using fixes from #153 (thanks @Bluskript ) - cos it works with the amman validator from #149

lots of typescript errors to work through, and more extract things to components.

BUT - I can now mint new tokens to an account that has an ATA for it from the programchanges page, so progress.

I'll force push this branch to #123 soon...

### CODE REVIEW

**Comment by nathanleclaire** [comment]
https://github.com/workbenchapp/solana-workbench/issues/161

**Comment by SvenDowideit** [comment]
OK, used GH's conflict resolution editing to bring things closer. more dev work later.

**Comment by SvenDowideit** [comment]
oh my, its working

**Comment by SvenDowideit** [comment]
pushed to main PR

**Pull request closed without merging**
