### PR TITLE
[WIP] Fix up some styles, re-add bootstrap grid

### PR DESCRIPTION
**Pull request by nathanleclaire**
Started in on a new feature splitting validator screen, sorely missed grid system. So I've re-added it, and simplified/cleaned up some styles we have elsewhere.

mostly looks the same -- spotted a couple UI issues -- 

Screen Shot 2022-07-11 at 4 07 25 PM

and table rows are back to equal space
Screen Shot 2022-07-11 at 4 08 30 PM
 now -- 

Signed-off-by: Nathan LeClaire <nathan@cryptoworkbench.io>

### CODE REVIEW

**Comment by nathanleclaire** [comment]
ah, also table row hover is broken, i'll look at fixing

**Comment by nathanleclaire** [comment]
bleh, this also overflows the devnet etc views ... 

Screen Shot 2022-07-11 at 4 34 40 PM

**Review by SvenDowideit — APPROVED** [review]
LGTM

**Comment by nathanleclaire** [comment]
this is hairier than i realized, i'm gonna look at seeing if tailwind grid can serve my original need that , between that and #194 might invalidate this PR

**Comment by nathanleclaire** [comment]
yea i think tailwind will give me what i want so closey closey 🚫

**Pull request closed without merging**
