### PR TITLE
don't crash if anchor cli can't be called

### PR DESCRIPTION
**Pull request by SvenDowideit**

### CODE REVIEW

**Comment by nathanleclaire** [comment]
hmm ... this is supposed to be handled by [this try-catch](https://github.com/workbenchapp/solana-workbench/blob/main/src/main/main.ts#L46-L102) so why isn't that working?

**Comment by SvenDowideit** [comment]
so when I say "crash" I mean we print a stacktrace - java style - because we're not actually handling the exception where it is.

so - the global try-catch "works", but only for the programmer, not to tell the user what's actually going on - this PR changes that.

**Comment by nathanleclaire** [comment]
[This line](https://github.com/workbenchapp/solana-workbench/blob/main/src/main/main.ts#L101) should communicate the error back to the main renderer, perhaps we're not listening for it?

**Comment by SvenDowideit** [comment]
no, I can't find anything that deals with the res object being anything other than an idl one - and the line you linked is the "OMG we totally didn't code for that" emergency catch - this isn't one of those - we know it can happen, and can tell the user something useful, not a random stack trace.

**Comment by nathanleclaire** [comment]
Got it -- that makes sense. Couple thoughts -- I agree this is a step in the right direction -- we should probably keep in mind as well to clean up the error messages (e.g., `Couldn't find the Anchor binary. Is it available in your $PATH?`)  This will just return the same error message as the oh shit catch at this point.

Also, we now have an `error` key that can appear in `res` as well as in `resp` -- that's kind of confusing, do you think there's a way we could clean that up somehow? (could nest the oh shit error in the `resp` on the back end for instance)

**Pull request merged**
