### PR TITLE
Clean up token page when no data

### LINKED ISSUE #209: 2 column view in tokens page is weird when there are no mints
yup - there's something i think should be better with the data lifecycle changes, but also yup

https://github.com/workbenchapp/solana-workbench/pull/123#issuecomment-1181212882

### LINKED ISSUE #232: fix the html issues introduced by the tokens work
Sven!

### PR DESCRIPTION
**Pull request by SvenDowideit**
closes #232
closes #209

### CODE REVIEW

**Comment by nathanleclaire** [comment]
I'm having a hard time testing this, cause something on main seems to blow up when I go to Tokens page --

Screen Shot 2022-07-15 at 10 02 38 AM

I'll have a looksie and see if I can spot the issue 

(Side note, my screen goes black and I can't navigate anywhere when that happens, can we prevent that type of thing from happening somehow?)

**Comment by nathanleclaire** [comment]
mmm, I think it's related to the ~100 errors we see with `npm exec tsc` directly, which is known issue from vite port iirc? do we have something to track that anywhere?

Screen Shot 2022-07-15 at 10 26 27 AM


Do our existing `tsc` commands in `npm run lint` even do anything anymore?

**Comment by Bluskript** [comment]
The problem is that `npx run tsc` isn't accurate because there is a `tsconfig.json` sitting inside of the renderer directory. I think this can be resolved by adding `**.*` to `"include"` in that json file, but yea running `tsc` directly will use the root tsconfig which isn't accurate.

**Comment by nathanleclaire** [comment]
> The problem is that npx run tsc isn't accurate because there is a tsconfig.json sitting inside of the renderer directory. I think this can be resolved by adding **.* to "include" in that json file, but yea running tsc directly will use the root tsconfig which isn't accurate.

I don't follow you. It isn't accurate how? It's printing what seem to be a bunch of valid errors. And the `main` and `renderer` tsconfigs look like they link back to the root one using `"extends": "../../tsconfig.json"`.

**Comment by SvenDowideit** [comment]
oh yay, frustrating.

**Comment by SvenDowideit** [comment]
@nathanleclaire so I get the 

```
MetaplexTokenData.tsx:29 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at DataPopover (MetaplexTokenData.tsx:29:29)
    at MetaplexTokenDataButton (MetaplexTokenData.tsx:214:16)
```

crash on the tokens page in `origin/main` at the moment - and _not_ with this PR's branch (I get a totally different one now :(

**Comment by nathanleclaire** [comment]
Yea same when I tested, seems to be a problem on `main`.

Got distracted w/ the TS errors, but we should just wait until after 0.4.0 to chip away at those.

**Comment by SvenDowideit** [comment]
ok, made https://github.com/workbenchapp/solana-workbench/pull/247 for that

**Comment by SvenDowideit** [comment]
no this is holding up too many other things. merging.

**Pull request merged**
