### PR TITLE
0.3.0version bump

### PR DESCRIPTION
**Pull request by SvenDowideit**
I hope this is what is needed :)

### CODE REVIEW

**Comment by nathanleclaire** [comment]
i've been leaving the `-alpha` off lately, thoughts?

**Comment by SvenDowideit** [comment]
argh, mega conflicted :) I want to have a practice were we communicate "upgrade, its worth it" vs "shaking out builds"

but yeah, i've never lived putting the marketing version number into the build...

**Comment by SvenDowideit** [comment]
really would prefer the version bump in the repo happen just after a version is uploaded, or even better, for it not to be in-repo files  (and yeah, several decades of build-engineer experience tells me there are zero good answers)

maybe versioning should be done as a watermark that is applied to a binary after build, backed by a blockchain :D

**Comment by nathanleclaire** [comment]
> really would prefer the version bump in the repo happen just after a version is uploaded

agreed, just fucked that up this go-round to laziness / spaziness . `0.4.0-dev` soon

**Pull request merged**
