### PR TITLE
Confirmation dialog added while exiting a window

### PR DESCRIPTION
**Pull request by sammanadh**

### CODE REVIEW

**Comment by sammanadh** [comment]
fixes #287

**Comment by nathanleclaire** [comment]
Nice. Is this ready for review? Lint/prettier has some issues in the CI you'll want to look at cleaning up. `npm run lint` locally should emit them locally for your review (My VScode also shows the integrated errors and runs prettier for me)

**Comment by nathanleclaire** [comment]
The guilty line seems to come from `@solana/web3.js` so I am going to try pinning that version to a specific one and deferring the bundling compatibility to another day. https://github.com/solana-labs/solana-web3.js/blob/895de4cd66614c0cffe79061016bdb9fa3d9a6ab/src/programs/address-lookup-table/state.ts#L36

If that doesn't unbreak the build, will look at other options

**Comment by nathanleclaire** [comment]
OK got it, package deps didn't need to change, just the ES target. I guess the default for Vite must be `es2019`. I bumped it to `es2021`, which is what our `tsconfig.json` has set anyway.

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
