### PR TITLE
Bump Solana to v1.9.20

### PR DESCRIPTION
**Pull request by nathanleclaire**
branch name wrong, but on the plus side --

Closes https://github.com/workbenchapp/solana-workbench/issues/89

### CODE REVIEW

**Comment by nathanleclaire** [comment]
i built and pushed the ARM image

**Comment by nathanleclaire** [comment]
Hang on, this needs a second... Some port issues on startup with the new version...

**Comment by nathanleclaire** [comment]
Screen Shot 2022-05-05 at 5 57 55 PM
sigh

**Comment by nathanleclaire** [comment]
OK! Widening up the port range seems to have made it happy.

There are a few other patches for things I ran into around log page bricking and wonky container start attempts.

This is good to go. Please review

**Review by SvenDowideit — APPROVED** [review]
LGTM

**Pull request merged**
