### PR TITLE
update to @solana/web3.js from 29/04/2022

### LINKED ISSUE #81: its possible to crash programchanges when changing networks
I was changing between local, dev, test, main, a few times, and eventually got this - we should basically just reset and continue.

(mmmm, and this was using the electron app from a browser, so maybe that makes it more/less likely)

actually, i might also have been hitting RPC request throttling - as i had ~3000 accounts listed from watching devnet, and then changed to testnet - and I think the code currently tries to get all those account's info?

image

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

closes #81

### CODE REVIEW

**Comment by SvenDowideit** [comment]
Bah, this will be easier to test on top of #94

**Comment by SvenDowideit** [comment]
yay, "works for me" :)

**Comment by nathanleclaire** [comment]
I think there were some subscription improvements in newer versions so this is great! Will test today

**Review by nathanleclaire — APPROVED** [review]

**Comment by nathanleclaire** [comment]
LGTM

**Pull request merged**
