### PR TITLE
Ux/tokens - create tokens (without metaplex meta data)

### LINKED ISSUE #63: Create local tokens and NFTs
We should have a nice UI to create regular old fungible tokens as well as NFTs (integrating with Metaplex).

### LINKED ISSUE #114: AccountView Token support
this is #123

We will be adding the feature to mint tokens (both fungible and non-fungible) via Workbench, and there are also lots of built-in tokens on mainnet etc. However, Workbench's account support and rendering of what's happening is pretty basic and low level right now and doesn't understand tokens.

This type of view ideally should show existing token balances, etc., or mint properties if it's a mint:

Screen Shot 2022-05-06 at 12 27 52 PM

Likewise once https://github.com/workbenchapp/solana-workbench/pull/73 lands it should show probably show diffs of tokens/SOL in txns like how explorer does

Screen Shot 2022-05-06 at 12 29 24 PM

### PR DESCRIPTION
**Pull request by SvenDowideit**
* [x] button for each token step
* [x] buttons are only enabled when the the wallet has authority to
* [x] default to call the token `WORKBENCH` and claim that TOKEN as developer testing
  * there is no metaplex program on localnet by default - i'm thinking to defer this to phase2 ...
* [x] use the wallet account for funder and default receiver
* [x] give the user a transfer token to another user button (with "create ata if needed" tickbox)
* [x] #80 save private keys if creating a new funder / receiver
  * [x] #126 simplify IPC and storage
  * [x] #129 remake the account save to backend
  * [x] #129 bring back edit human name
* [x] #134 use wallet-adapter to do signing
* [x] add accountview for funder&ATS&tokens, Mint, receiver&ATA&tokens

* #200 Show reason for error minting etc - `react_devtools_backend.js:4061 WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.`
* #199 NEXTPR: upload image/whatever for ntf
* #201 NEXTPR: move the create new private key code to backend (but continue to let the frontend use the private key for inline signing)
* #202 NEXTPR:  move all transaction signing to backend via wallet-adapter
* #203 the tokenPage view when there is no on-chain account for the electron wallet (tell the user they need to fund it)
* #204 the tokenPage view when the account has no mint, or the mint is partially defined...
* #205 "ARE YOU SURE" popup for close mint - its kinda finallll

closes #63
closes #114

kinda requires #79 and #82

### CODE REVIEW

**Comment by nathanleclaire** [comment]
So here's a thought -- for the metaplex stuff -- we could bundle https://github.com/metaplex-foundation/amman in the container and use it to start the validator instead of the direct `solana-test-validator` command we use today... Amman can be configured to pull down programs from mainnet and caches them, so we could use a volume for that stateful bit ... Only possible issue is I don't see any direct way to use `--no-bpf-jit` which was needed for me to get the validator to play nice in Docker

**Comment by nathanleclaire** [comment]
https://github.com/workbenchapp/solana-workbench/issues/161

**Comment by SvenDowideit** [comment]
its useable, I'm thinking to merge and then fix soon

image

**Comment by nathanleclaire** [comment]
Definitely some stuff I want to clean up on this before we merge it, since it's breaking existing functionality -- will post some comments as well as general UI feedback

**Comment by nathanleclaire** [comment]
Clicking around on accounts now feels confusing to me -- they take longer to load up and it feels mushy, like I'm not sure what I'm really looking at. Can we speed it up or maybe at least add a loading spinner?


https://user-images.githubusercontent.com/1476820/178388239-ee5eddf0-adc7-48e1-8240-486579a5eeca.mov



Alternatively -- do we need to embed the associated mints etc in the account view at all? Token accounts, sure, but mints have their own tab no? (or they could be pinned if user wanted to look at them in account view)

**Comment by nathanleclaire** [comment]
Screen Shot 2022-07-11 at 6 21 18 PM

I get this unable to find account error, not sure what's causing it but it seems unique to token PR

**Comment by nathanleclaire** [comment]
Why the duplicated Data field? 
image

**Comment by nathanleclaire** [comment]
The two columns here was kinda confusing, could you maybe hide the content of the second pane if there are no mints detected, and say something like "Token mints will appear here once created"?

image

**Comment by nathanleclaire** [comment]
Since we know this is a wallet, should we hide the Data field? It won't ever be set 
image

(Come to think of it, we should probably do this in account view too)

**Comment by nathanleclaire** [comment]
Maybe we want to put just this section in there vs. the whole thing? It's the highest information bit  

image

**Comment by nathanleclaire** [comment]
Lots of duplication of the same stuff, not clear to me where to click to do what -- can we reduce this to one clear way to edit metadata? same w/ airdrops, transfer sol, etc 

image

Probably take out the ability to create the mints from the Account view if we're going to have a separate page for it? (I like separate page) That would hopefully simplify integrating this into the Account view a bit

**Comment by nathanleclaire** [comment]
Also, I didn't even realize the gray buttons were disabled tbh. Maybe throw `cursor: none;` on there to make it more clear, and add some opacity? 

Cleaning up `Account` view is really the main thing I want to get this merged! Other stuff, I'm just scribbling down to track. Cool stuff.

**Comment by SvenDowideit** [comment]
nice! lots of things that were "yeah, need to get to that" that got lost in the haze of making it work.

fun fact - the token page is _actually_ just two AccountView's - one of the user's electron wallet adapter, and the other of the "selected mint".

personally, i find that page redundant, and I use the programchanges for all the token actions - but fixes to one, carry on to the other :)

and the real kicker - the delay in loading the Account View - exactly - that's the data lifecycle thing I was talking about being the main thing I'll work on for the week - and yeah, the AccountView subcomponents need some kind of spinner UX - cos eventually, finding out the list of ATA's takes longer than the user likes.

(and a solid nope to removing the mint bits from AccountView - i needs it! :p)

**Comment by SvenDowideit** [comment]
ok, lots of issues created for all that, i'm going to merge, so i can fix them in smaller chunks without losing what the change was for on squash-merge :)

**Pull request merged**
