### PR TITLE
Fix native anchor dependency problem

### PR DESCRIPTION
**Pull request by Bluskript**

### CODE REVIEW

**Comment by Bluskript** [comment]
Note: currently it freezes for some reason when switching to devnet. but... somehow that isn't related to any of the changes because when i comment out the anchor data fetching it still freezes. understanding whats broken TODO

**Comment by nathanleclaire** [comment]
I don't really understand how this code works even in a regular browser.

```typescript
export const isBrowser =
  process.env.BROWSER ||
  (typeof window !== "undefined" && !window.process?.hasOwnProperty("type"));
```

If I just pop that in my console and try it, I get the same error about `process` not being defined. Is there some magic when Anchor bundles up the package?

**Comment by nathanleclaire** [comment]
So -- thinking about it some more -- probably there is some way that `process.env` gets transformed into something palatable for browsers by the Anchor module's build? Otherwise it would not run in the browser, and that is clearly something people do. Perhaps it is https://webpack.js.org/plugins/environment-plugin/ ?

If so, do we need something like https://github.com/ElMassimo/vite-plugin-environment ? Or am I totally off base here?

**Comment by nathanleclaire** [comment]
Oh goodness, it's looking like https://github.com/ElMassimo/vite-plugin-environment might well have done the trick ... 

Screen Shot 2022-07-01 at 6 22 08 PM

Am I ... am I learning about JS build pipelines? I'm scared

**Comment by nathanleclaire** [comment]
Gonna close this as I don't think it's quite right, but thanks for jamming on it with me @Bluskript !

**Pull request closed without merging**
