### PR TITLE
Moving native dep to release

### PR DESCRIPTION
**Pull request by sammanadh**
A native dependency was in root package.json. Removed it form there and installed it inside release/app.

### CODE REVIEW

**Comment by nathanleclaire** [comment]
This one's blowing up on me with compilation errors -- 

Screen Shot 2022-06-07 at 3 06 09 PM

we saw pretty much this exact issue before and solved it by moving the solana dep to `devDependencies`, i'm gonna try that locally and see if it works

**Comment by nathanleclaire** [comment]
yea it works fine with this 

```diff
diff --git a/package.json b/package.json
index f3958a9..3e7e0d8 100644
--- a/package.json
+++ b/package.json
@@ -151,6 +151,7 @@
   "devDependencies": {
     "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
     "@solana/web3.js": "^1.41.3",
+    "@solana/wallet-adapter-wallets": "^0.15.5",
     "@teamsupercell/typings-for-css-modules-loader": "^2.5.1",
     "@testing-library/jest-dom": "^5.16.1",
     "@testing-library/react": "^13.2.0",
diff --git a/release/app/package.json b/release/app/package.json
index ed7805c..b0dd8a0 100644
--- a/release/app/package.json
+++ b/release/app/package.json
@@ -16,6 +16,5 @@
   },
   "license": "MIT",
   "dependencies": {
-    "@solana/wallet-adapter-wallets": "^0.15.5"
   }
 }
```

can you update the PR to do that instead?

**Comment by sammanadh** [comment]
Yup, works fine in my end as well. Have pushed those changes. Please verify.

**Comment by sammanadh** [comment]
I have one concern though. Wouldn't this break our app in production build. Or is this package only required for development?

**Comment by nathanleclaire** [comment]
Yea that confused us too with `@solana/web3.js` but everything seems to work fine with the package 🤷 

LGTM

**Pull request merged**
